meta_product_name: "maÏa"
meta_title: "Suivez et partagez le quotidiens de votre enfant"
meta_description: "Nouvelle application pour nounous et parents"
meta_image: "maia-logo.png" # should exist in `app/assets/images/`
